"""
Report Builder
Constructs multi-format reports (Markdown, PDF) from generated intelligence.
"""

class ReportBuilder:
    def __init__(self):
        pass

    def build_markdown_report(self, data: dict) -> str:
        # TODO: Implement report builder
        return "# Research Report\n\nGenerated by QORA."
